export const CREATE_JOURNAL_REQUEST = "CREATE_JOURNAL_REQUEST";
export const CREATE_JOURNAL_SUCCESS = "CREATE_JOURNAL_SUCCESS";
export const CREATE_JOURNAL_ERROR = "CREATE_JOURNAL_ERROR";

export const GET_ACCOUNT_TYPE_REQUEST = "GET_ACCOUNT_TYPE_REQUEST";
export const GET_ACCOUNT_TYPE_SUCCESS = "GET_ACCOUNT_TYPE_SUCCESS";
export const GET_ACCOUNT_TYPE_ERROR = "GET_ACCOUNT_TYPE_ERROR";

export const CREATE_ACCOUNT_TYPE_REQUEST = "CREATE_ACCOUNT_TYPE_REQUEST";
export const CREATE_ACCOUNT_TYPE_SUCCESS = "CREATE_ACCOUNT_TYPE_SUCCESS";
export const CREATE_ACCOUNT_TYPE_ERROR = "CREATE_ACCOUNT_TYPE_ERROR";