export const BILL_LIST_REQUEST = "BILL_LIST_REQUEST";
export const BILL_LIST_SUCCESS = "BILL_LIST_SUCCESS";
export const BILL_LIST_ERROR = "BILL_LIST_ERROR";

export const BILL_DETAILS_REQUEST = "BILL_DETAILS_REQUEST";
export const BILL_DETAILS_SUCCESS = "BILL_DETAILS_SUCCESS";
export const BILL_DETAILS_ERROR = "BILL_DETAILS_ERROR";