export const FETCH_MASTER_DATA_REQUEST = "FETCH_MASTER_DATA_REQUEST";
export const FETCH_MASTER_DATA_SUCCESS = "FETCH_MASTER_DATA_SUCCESS";
export const FETCH_MASTER_DATA_FAILURE = "FETCH_MASTER_DATA_FAILURE";

export const COUNTRY_DATA_REQUEST = "COUNTRY_DATA_REQUEST";
export const COUNTRY_DATA_SUCCESS = "COUNTRY_DATA_SUCCESS";
export const COUNTRY_DATA_FAILURE = "COUNTRY_DATA_FAILURE";


export const CITY_DATA_REQUEST = "CITY_DATA_REQUEST";
export const CITY_DATA_SUCCESS = "CITY_DATA_SUCCESS";
export const CITY_DATA_FAILURE = "CITY_DATA_FAILURE";

export const STATE_DATA_REQUEST = "STATE_DATA_REQUEST";
export const STATE_DATA_SUCCESS = "STATE_DATA_SUCCESS";
export const STATE_DATA_FAILURE = "STATE_DATA_FAILURE";

export const ACITVE_INACTIVE_REQUEST = "ACITVE_INACTIVE_REQUEST";
export const ACITVE_INACTIVE_SUCCESS = "ACITVE_INACTIVE_SUCCESS";
export const ACITVE_INACTIVE_FAILURE = "ACITVE_INACTIVE_FAILURE";

export const CREATE_CUSTOM_FIELD_REQUEST = "CREATE_CUSTOM_FIELD_REQUEST";
export const CREATE_CUSTOM_FIELD_SUCCESS = "CREATE_CUSTOM_FIELD_SUCCESS";
export const CREATE_CUSTOM_FIELD_FAILURE = "CREATE_CUSTOM_FIELD_FAILURE";

export const GET_CURRENCY_REQUEST = "GET_CURRENCY_REQUEST";
export const GET_CURRENCY_SUCCESS = "GET_CURRENCY_SUCCESS";
export const GET_CURRENCY_ERROR = "GET_CURRENCY_ERROR";

export const GET_TAX_RATE_REQUEST = "GET_TAX_RATE_REQUEST";
export const GET_TAX_RATE_SUCCESS = "GET_TAX_RATE_SUCCESS";
export const GET_TAX_RATE_ERROR = "GET_TAX_RATE_ERROR";