export const FETCH_MASTER_DATA_REQUEST = "FETCH_MASTER_DATA_REQUEST";
export const FETCH_MASTER_DATA_SUCCESS = "FETCH_MASTER_DATA_SUCCESS";
export const FETCH_MASTER_DATA_FAILURE = "FETCH_MASTER_DATA_FAILURE";

export const COUNTRY_DATA_REQUEST = "COUNTRY_DATA_REQUEST";
export const COUNTRY_DATA_SUCCESS = "COUNTRY_DATA_SUCCESS";
export const COUNTRY_DATA_FAILURE = "COUNTRY_DATA_FAILURE";


export const CITY_DATA_REQUEST = "CITY_DATA_REQUEST";
export const CITY_DATA_SUCCESS = "CITY_DATA_SUCCESS";
export const CITY_DATA_FAILURE = "CITY_DATA_FAILURE";

export const STATE_DATA_REQUEST = "STATE_DATA_REQUEST";
export const STATE_DATA_SUCCESS = "STATE_DATA_SUCCESS";
export const STATE_DATA_FAILURE = "STATE_DATA_FAILURE";