export const ADD_ITMES_REQUEST = "ADD_ITMES_REQUEST";
export const ADD_ITMES_SUCCESS = "ADD_ITMES_SUCCESS";
export const ADD_ITMES_ERROR = "ADD_ITMES_ERROR";

export const STOCK_ITMES_REQUEST = "STOCK_ITMES_REQUEST";
export const STOCK_ITMES_SUCCESS = "STOCK_ITMES_SUCCESS";
export const STOCK_ITMES_ERROR = "STOCK_ITMES_ERROR";

export const ITMES_DETAIL_REQUEST = "ITMES_DETAIL_REQUEST";
export const ITMES_DETAIL_SUCCESS = "ITMES_DETAIL_SUCCESS";
export const ITMES_DETAIL_ERROR = "ITMES_DETAIL_ERROR";