export const FETCH_CAT_LIST_DATA_REQUEST = 'FETCH_CAT_LIST_DATA_REQUEST';
export const FETCH_CAT_LIST_DATA_SUCCESS = 'FETCH_CAT_LIST_DATA_SUCCESS';
export const FETCH_CAT_LIST_DATA_FAILURE = 'FETCH_CAT_LIST_DATA_FAILURE';

export const FETCH_ITEM_LIST_DATA_REQUEST = 'FETCH_ITEM_LIST_DATA_REQUEST';
export const FETCH_ITEM_LIST_DATA_SUCCESS = 'FETCH_ITEM_LIST_DATA_SUCCESS';
export const FETCH_ITEM_LIST_DATA_FAILURE = 'FETCH_ITEM_LIST_DATA_FAILURE';

export const FETCH_ACC_LIST_DATA_REQUEST = 'FETCH_ACC_LIST_DATA_REQUEST';
export const FETCH_ACC_LIST_DATA_SUCCESS = 'FETCH_ACC_LIST_DATA_SUCCESS';
export const FETCH_ACC_LIST_DATA_FAILURE = 'FETCH_ACC_LIST_DATA_FAILURE';

export const FETCH_QUOTE_LIST_DATA_REQUEST = 'FETCH_QUOTE_LIST_DATA_REQUEST';
export const FETCH_QUOTE_LIST_DATA_SUCCESS = 'FETCH_QUOTE_LIST_DATA_SUCCESS';
export const FETCH_QUOTE_LIST_DATA_FAILURE = 'FETCH_QUOTE_LIST_DATA_FAILURE';

export const FETCH_SALE_LIST_DATA_REQUEST = "FETCH_SALE_LIST_DATA_REQUEST";
export const FETCH_SALE_LIST_DATA_SUCCESS = "FETCH_SALE_LIST_DATA_SUCCESS";
export const FETCH_SALE_LIST_DATA_FAILURE = "FETCH_SALE_LIST_DATA_FAILURE";

export const FETCH_INVOICE_LIST_DATA_REQUEST = "FETCH_INVOICE_LIST_DATA_REQUEST";
export const FETCH_INVOICE_LIST_DATA_SUCCESS = "FETCH_INVOICE_LIST_DATA_SUCCESS";
export const FETCH_INVOICE_LIST_DATA_FAILURE = "FETCH_INVOICE_LIST_DATA_FAILURE";

export const FETCH_CREDIT_LIST_DATA_REQUEST = "FETCH_CREDIT_LIST_DATA_REQUEST";
export const FETCH_CREDIT_LIST_DATA_SUCCESS = "FETCH_CREDIT_LIST_DATA_SUCCESS";
export const FETCH_CREDIT_LIST_DATA_FAILURE = "FETCH_CREDIT_LIST_DATA_FAILURE";


export const FETCH_VENDOR_LIST_DATA_REQUEST = "FETCH_VENDOR_LIST_DATA_REQUEST";
export const FETCH_VENDOR_LIST_DATA_SUCCESS = "FETCH_VENDOR_LIST_DATA_SUCCESS";
export const FETCH_VENDOR_LIST_DATA_FAILURE = "FETCH_VENDOR_LIST_DATA_FAILURE";

