export const CREDIT_NOTE_DETAIL_REQUEST = "CREDIT_NOTE_DETAIL_REQUEST";
export const CREDIT_NOTE_DETAIL_SUCCESS = "CREDIT_NOTE_DETAIL_SUCCESS";
export const CREDIT_NOTE_DETAIL_ERROR = "CREDIT_NOTE_DETAIL_ERROR";

export const CREDIT_NOTE_DELETE_REQUEST = "CREDIT_NOTE_DELETE_REQUEST";
export const CREDIT_NOTE_DELETE_SUCCESS = "CREDIT_NOTE_DELETE_SUCCESS";
export const CREDIT_NOTE_DELETE_ERROR = "CREDIT_NOTE_DELETE_ERROR";