export const QUOTATION_DETAIL_REQUEST = "QUOTATION_DETAIL_REQUEST";
export const QUOTATION_DETAIL_SUCCESS = "QUOTATION_DETAIL_SUCCESS";
export const QUOTATION_DETAIL_ERROR = "QUOTATION_DETAIL_ERROR";


// Constants for updating quotation
export const QUOTATION_UPDATE_REQUEST = 'QUOTATION_UPDATE_REQUEST';
export const QUOTATION_UPDATE_SUCCESS = 'QUOTATION_UPDATE_SUCCESS';
export const QUOTATION_UPDATE_ERROR = 'QUOTATION_UPDATE_ERROR';
