export const VIEW_VENDOS_VIEW_REQUEST = "VIEW_CUSTOMER_REQUEST";
export const VIEW_VENDOS_VIEW_SUCCESS = "VIEW_CUSTOMER_SUCCESS";
export const VIEW_VENDOS_VIEW_ERROR = "VIEW_VENDOS_ERROR";

export const CREATE_VENDOS_REQUEST = "CREATE_VENDOS_REQUEST";
export const CREATE_VENDOS_SUCCESS = "CREATE_VENDOS_SUCCESS";
export const CREATE_VENDOR_ERROR = "CREATEEW_VENDEW_ERROR";