export const VIEW_VENDOS_VIEW_REQUEST = "VIEW_CUSTOMER_REQUEST";
export const VIEW_VENDOS_VIEW_SUCCESS = "VIEW_CUSTOMER_SUCCESS";
export const VIEW_VENDOS_VIEW_ERROR = "VIEW_VENDOS_ERROR";

export const CREATE_VENDOS_REQUEST = "CREATE_VENDOS_REQUEST";
export const CREATE_VENDOS_SUCCESS = "CREATE_VENDOS_SUCCESS";
export const CREATE_VENDOR_ERROR = "CREATEEW_VENDEW_ERROR";



// VENDOS_STATUS_REQUEST,
//     VENDOS_STATUS_SUCCESS,
//     VENDOR_STATUS_ERROR,

//     VENDOS_DELETE_REQUEST,
//     VENDOS_DELETE_SUCCESS,
//     VENDOR_DELETE_ERROR